### ISSUE TITLE
Add documentation on how to implement SSL pinning

### ISSUE THREAD

**Issue by tylermilner** [BottleRocketStudios/iOS-Hyperspace#108]
I know this feature was added a while back, but I'm going to need to look through the code now that I'm getting ready to use it. It would be nice if we included some basic info on how to use SSL pinning in Hyperspace in the `README` or in the `/Documentation` folder.

**Comment by wmcginty** [comment]
I've added an `SSL Pinning` document in #154 that should address this (or at least start on it)
