### ISSUE TITLE
Improve error handling

### ISSUE THREAD

**Issue by earlgaspard** [BottleRocketStudios/iOS-Hyperspace#112]
Error handling needs to account for:
Errors that return responses
200s that are actual failures (if possible. this may be project related)

**Comment by tylermilner** [comment]
This is currently possible, but a little messy. Another ticket meant for Hyperspace rewrite tracking?

**Comment by earlgaspard** [comment]
I am unaware of the rewrite plans but I don't see why it can't be part of it.

**Comment by wmcginty** [comment]
There are some enhancements here in #117

**Comment by wmcginty** [comment]
I'm going to close this one out. Hyperspace supports the ability for an end user to specify their own custom error type (other than `AnyError`, which provides some powerful advanced error handling options. In addition, there are guides for error [handling](https://github.com/BottleRocketStudios/iOS-Hyperspace/blob/main/Documentation/Guides/Error%20Handling.md) and [recovery](https://github.com/BottleRocketStudios/iOS-Hyperspace/tree/main/Documentation/Guides) that can aid with specifics.
