### ISSUE TITLE
Handle empty responses

### ISSUE THREAD

**Issue by earlgaspard** [BottleRocketStudios/iOS-Hyperspace#113]
Implement a way for Hyperspace to handle empty responses easily.

**Comment by tylermilner** [comment]
This is currently possible. Is this ticket more about tracking improved functionality for the Hyperspace rewrite?

**Comment by earlgaspard** [comment]
It is currently possible but not ideal. My project had to create its own empty response and use force casting to get this to work. Definitely should go in the rewrite.
