### ISSUE TITLE
Support decoding strategies

### ISSUE THREAD

**Issue by earlgaspard** [BottleRocketStudios/iOS-Hyperspace#115]
Implement a way for Hyperspace to support various decoding strategies.

**Comment by tylermilner** [comment]
You should already be able to decode into any type of object via the `transformSuccess(_:)` method on the `Request` protocol. Is this issue to track requirements for the Hyperspace rewrite?

**Comment by earlgaspard** [comment]
This issue was created after discussing Hyperspace improvements. I am not sure what decoding strategies were needed. Maybe it was making Hyperspace improvements to make supporting  `keyDecodingStrategy`s easier. This issue was not added to track requirements for a rewrite.

**Comment by wmcginty** [comment]
I'm going to close this one out. Hyperspace supports the ability to provide a custom `JSONDecoder` as well as a closure that use any method desired to convert the provided `TransportSuccess` into the expected `Response`. If there are specific  requests for flexibility in the future, we can open new issues.
