### ISSUE TITLE
Hyperspace on WatchOS

### ISSUE THREAD

**Issue by GrandLarseny** [BottleRocketStudios/iOS-Hyperspace#119]
Just ran into an interesting issue where Hyperspace would not work when installed as a dependency of a framework that has `watchOS` as its Base SDK.

Changing the framework's Base SDK from `watchOS` to `iOS` allowed the framework to build just fine, but it couldn't be used by the watch app directly. I imagine that up until now having a WatchKit extension has been just fine, and maybe it always will be, but it'd be nice to be able to use Hyperspace in a watchOS-exclusive app.

**Comment by tylermilner** [comment]
I agree, we should allow Hyperspace to be used by the new standalone watchOS apps. Since we've had WatchKit extension support for a while now, I can't imagine this would be something terribly difficult to do...

**Comment by GrandLarseny** [comment]
Ugggghhhh, I am the problem. Turns out I had my `Podfile` screwed up, set the platform to `:ios` instead of `:watchos` and `:ios` per target. Once I had my `Podfile` right everything is working.
