### ISSUE TITLE
Increase default timeout to 60s

### ISSUE THREAD

**Issue by tylermilner** [BottleRocketStudios/iOS-Hyperspace#122]
Is a 30 second default timeout for requests too small?

**Comment by earlgaspard** [comment]
Maybe. Has Hyperspace always been set to a 30 second default?
Going to 60 seconds is fine with me because it is the default Apple uses with URLSession.
[timeoutIntervalForRequest](https://developer.apple.com/documentation/foundation/nsurlsessionconfiguration/1408259-timeoutintervalforrequest)
