### ISSUE TITLE
EXC_BAD_ACCESS in TransportService.swift:46

### ISSUE THREAD

**Issue by GrandLarseny** [BottleRocketStudios/iOS-Hyperspace#144]
It appears that Hyperspace isn't thread safe. I've encountered this scenario a few times where executing multiple requests asynchronously will result in sporadic `EXC_BAD_ACCESS` errors at `TransportService.swift:46`. See the following screenshot:

![LLDB access error](https://user-images.githubusercontent.com/583988/143957006-1d6a1095-c9d7-4a28-b521-5fc13a86b7f3.png)

As you can see in the screenshot, there is another thread in the `execute()` function when the crash occurs. I believe that this error is occurring because of a data race inside the execute function when modifying the `tasks` variable. 

My first suggestion is to change `TransportService` to be an `actor` instead of `class`. This should alleviate the problems with concurrent network executions. 

Of course, this means that `TransportService` will be asynchronous, which is a pretty big overhaul. I do understand if this seems to big a break, even for a major release. 

So, skipping back a beat, my second suggestion will be to do all `tasks` work on a dispatch queue, wrapping all references to `tasks` in an async block. Similar to the approach suggested here: https://www.swiftbysundell.com/articles/swift-actors

Open to suggestions!

**Comment by wmcginty** [comment]
I think for now the better solution would be to wrap `execute` (or just access to `tasks`) in a serial `DispatchQueue` to minimize the surface of changes.

I would imagine that fully adopting the new Swift concurrency model will bring about a larger set of changes that make sense for a 5.0 release.

**Comment by GrandLarseny** [comment]
Yeah, sounds good to me. I'll make the changes and submit a PR.

**Comment by GrandLarseny** [comment]
PR https://github.com/BottleRocketStudios/iOS-Hyperspace/pull/145 ready for review

**Comment by wmcginty** [comment]
Fixed in #145 .
