### ISSUE TITLE
Crash: specialized Dictionary._Variant.isUniquelyReferenced()

### ISSUE THREAD

**Issue by keyvanygh** [BottleRocketStudios/iOS-Hyperspace#174]
Getting crashes with the title of "swift_isUniquelyReferenced_nonNull_native", the stack trace points to this line of code in "NetworkService" Class extension.

❗tasks[request] = task

pod 'Hyperspace/Pinning', '=3.2.1'

<img width="867" alt="Screenshot 2024-05-17 at 11 57 09 AM" src="https://github.com/BottleRocketStudios/iOS-Hyperspace/assets/24761725/15be9e26-73c4-4d8f-b892-d9a8e916b345">

**Comment by rmirabelli** [comment]
This has been fixed in a later version of this project (4.0) (https://github.com/BottleRocketStudios/iOS-Hyperspace/pull/145)

**Comment by rmirabelli** [comment]
Won't port the fix backward.
