### ISSUE TITLE
Improve documentation with solutions to common scenarios

### ISSUE THREAD

**Issue by tylermilner** [BottleRocketStudios/iOS-Hyperspace#42]
We should add some supporting documentation for how to deal with common scenarios like
* Customizing the `JSONDecoder` that's used
* How to deal with requests that don't return a response object (we have a playground for this already)

**Comment by wmcginty** [comment]
I created a Documentation/Guides and Documentation/Migrations folders. I've also begun an ErrorHandling guid. I think this would be a good place to build on our non-code documentation.

**Comment by tylermilner** [comment]
@wmcginty I think this is good for now. Now that we have a place to put the markdown files, we can add more guides as we go forward.
