### ISSUE TITLE
Add macOS Example

### ISSUE THREAD

**Issue by tylermilner** [BottleRocketStudios/iOS-Hyperspace#6]
We've got support for iOS, tvOS, and watchOS, along with examples for all three platforms. It shouldn't be too hard to implement a macOS example if we follow the conventions of the other examples. The bulk of the work will be:
* Framework
    * Create a "Hyperspace-macOS" framework target, adding the ~12 Hyperspace source files.
    * Follow the conventions to set the target's Module name, Product name, and Info.plist location appropriately.
    * Create a "Hyperspace-macOSTests" unit test target (if it's not created by now) and add the test source files as was done in the other framework test targets.
* Example
    * Creating an interface for macOS in Interface Builder.
    * Implementing the NSViewController (or however that works on Mac).

**Comment by andrew-winn-br** [comment]
Working on it. I guess we could have both Catalyst and AppKit examples...

**Comment by tylermilner** [comment]
@andrew-winn-br thanks for taking this on! I'm not sure how much work you've put into it, but you might want to wait until #117 is merged (or start work off of the `feature/refactors` branch). The changes in that branch will necessitate a major version release so, if possible, I'd definitely like to include macOS/Catalyst support as part of that as well. Of course, if you're already really close to having this working, go ahead and submit a PR and we'll just make @wmcginty deal with the merge. 😈

**Comment by andrew-winn-br** [comment]
@tylermilner I can hold off until 117.

**Comment by tylermilner** [comment]
@andrew-winn-br #117 was merged a few days ago. Feel free to resume work on this, branching off of `master`, if you're still interested and have time.

**Comment by andrew-winn-br** [comment]
@tylermilner Sounds good. Still interested.

**Comment by wmcginty** [comment]
Support through SPM and Cocoapods should now exist as of #151 - would be awesome to have a macOS / Catalyst example!

**Comment by andrew-winn-br** [comment]
Whoops yeah forgot about this! I can get on it.
