### ISSUE TITLE
Add code coverage badge

### ISSUE THREAD

**Issue by tylermilner** [BottleRocketStudios/iOS-Hyperspace#7]
Investigate and integrate the code coverage badge into the Readme. [Codecov](https://codecov.io/) looks to be one possible provider, but there could be others.

**Comment by achappell** [comment]
I've used codecov and really like it.

**Comment by achappell** [comment]
Code beat is another cool repo health tool that could be cool to look at

**Comment by tylermilner** [comment]
At first glance, Codebeat looks awesome! I couldn't tell if it does the code coverage badge, but even if it doesn't, we should look into integrating with it. It looks pretty awesome for internal projects too.

**Comment by wmcginty** [comment]
+1 for Codebeat. I've used it a few times before and it's very useful.
